function loadPage()
{
	// addQuestion(Question, Answer1, Answer2, Answer3, Answer4, CorrectAnswer [not 0-indexed])
	curPage = "quiz2.html";
	curQuiz = 2;
	curQuizRedirect=13;
	addQuestion("Based on the below quote from a book, which in-text citation is formatted correctly?<br>Author: <i>The Genius in All of Us</i><br>Page number 12<br>Quote: I am arguing that few of us ever get to know our own true potential, and that many of us mistake early difficulties for innate limits.<br>", "\"Few of us ever get to know our own true potential\" (<i>The Genius in All of Us</i>, 12)", "According to David Shenk, \"few of ever get to know our own true potential\" (12).", "David Shenk argues that \"few of us ever get to know our own true potential.\" (page 12)", "In <i>The Genius in All of Us</i>, David Shenk states, \"few of us ever get to know our own true potential\" (Shenk).", 2);
	addQuestion("Based on the below quote from a book, which in-text citation is formatted correctly?<br>Author: Malcolm Gladwell<br>Title: <i>Outliers</i><br>Page number 31<br>Quote: The second implication of the hockey example is the systems we set up to determine who gets ahead aren't particularly efficient.<br>", "Malcolm Gladwell explains that \"the systems we set up to determine who gets ahead aren't particularly efficient\" (31).", "In Outliers, Gladwell argues that \"the systems we set up to determine who gets ahead aren't  particularly efficient\" (pg31).", "\"The systems we set up to determine who gets ahead aren't particularly efficient.\" (Gladwell)", "According to Gladwell, the systems we set up to determine who gets ahead aren't particularly efficient (outliers, page 31).", 1);
	addQuestion("Based on the below quote from a journal article, which in-text citation is formatted correctly?<br>Author: Tharina Guse<br>Title: \"Enhancing Lives: A positive Psychology agenda for Hypnotherapy\"<br>Page number 216<br>Quote: Hypnotherapy focuses on mobilizing unconscious processes to facilitate healing.<br>", "According to Tharina Guse, \"hypnotherapy focuses on mobilizing unconscious processes to facilitate healing.\" (pg 216)", "In the article \"enhancing lives\", Tharina Guse explains that hypnotherapy focuses on mobilizing unconscious processes to facilitate healing.", "Some positive psychologists incorporate hypnotherapy, which \"focuses on mobilizing unconscious processes to facilitate healing\" (Guse 216)", "The article \"enhancing lives\" clarifies hypnotherapy, stating that is \"focuses on mobilizing unconscious processes to facilitate healing.\" (Guse, page 216)", 3);
	addQuestion("Based on the below online news article, which in-text citation is formatted correctly? <br>Authors: Andrew Jacobs and Ian Johnson<br>Title: \"Pollution killed 7 Million People Worldwide in 2012, Report Finds\"<br>Page number: no page numbers listed  <br>Quote: Breakneck urbanization in the developing nations of Asia, especially China, is a major force contributing to the air pollution problem.<br>", "Jacobs and Johnson state that \"breakneck urbanization in the developing nations of Asia, especially China, is a major force contributing to the air pollution problem.\"", "In the article, \"Pollution Killed 7 Million People Worldwide in 2012,\" readers learn that breakneck urbanization in the developing nations of Asia, especially China, is a major force contributing to the air pollution problem.", "A 2012 report explains that \"breakneck urbanization in the developing nations of Asia, especially China, is a major force contributing to the air pollution problem\" (Jacobs and Johnson).", "Both 1 and 3 are correct", 4);

	//----------------------------------------------------------
	display();
}